version: '3.4'
services:
  prysm-beacon-chain.avado.dnp.dappnode.eth:
    image: 'prysm-beacon-chain.avado.dnp.dappnode.eth:0.1.7'
    build: ./build
    volumes:
      - 'data:/data'
    ports:
      - '4000:4000'
      - '13000:13000'
    restart: always
volumes:
  data: {}
