version: '3.4'
services:
  prysm-beacon-chain-mainnet.avado.dnp.dappnode.eth:
    image: 'prysm-beacon-chain-mainnet.avado.dnp.dappnode.eth:0.0.39'
    build:
      context: ./build
      args:
        VERSION: v2.0.5
    volumes:
      - 'data:/data'
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '4000'
    restart: always
    environment:
      - >-
        EXTRA_OPTS=--http-web3provider=http://ethchain-geth.my.ava.do:8545
        --grpc-gateway-corsdomain=http://prysm-beacon-chain-mainnet.my.ava.do,http://eth2validator.my.ava.do
volumes:
  data: {}
